server:
   port: 9011
   servlet:
      context-path: /
   tomcat:
      uri-encoding: UTF-8
eureka:
   instance:
      # 使用 ip 代替实例名
      prefer-ip-address: true
      # 实例的主机名
      hostname: ${spring.cloud.client.ip-address}
      # 实例的 ID 规则
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
   client:
      serviceUrl:
         # 注册中心地址
         defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
   http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
   messages:
      encoding: UTF-8
   devtools:
      livereload:
         enabled: true
   redis:
      password: pbcom135789@123456
      timeout: 6000ms
      cluster:
         nodes: 39.107.92.210:7000,39.107.92.210:7001,39.107.92.210:7002,39.107.92.210:7003,39.107.92.210:7004,39.107.92.210:7005
         max-redirects: 3
      lettuce:
         pool:
            max-active: 200 #连接池最大连接数（使用负值表示没有限制）
            max-idle: 10 # 连接池中的最大空闲连接
            min-idle: 2 #连接池中的最小空闲连接
            max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
   activemq:
      broker-url: tcp://123.56.208.92:61616
      user: admin
      password: admin
      close-timeout: 15s   # 在考虑结束之前等待的时间
      in-memory: false      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
      non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
      send-timeout: 0     # 等待消息发送响应的时间。设置为0等待永远。
      packages:
         trust-all: true #不配置此项，会报错
      pool:

         enabled: true
         max-connections: 10   #连接池最大连接数
         idle-timeout: 30000   #空闲的连接过期时间，默认为30秒

mybatis:
   # type-aliases扫描路径
   type-aliases-package: package com.pbkj.hgs_cloud.hgs_framework.domain
   # mapper xml实现扫描路径
   mapper-locations: classpath*:mapper/*.xml
   configuration:
      jdbc-type-for-null: null
      map-underscore-to-camel-case: true #配置驼峰命名转换 在进行sql查询和初始化实体时mybatis会为我们自动转化

mapper:
   mappers: com.pbkj.hgs_cloud.hgs_framework.config.BaseMapper
   not-empty: false
   identity: MYSQL
#输出日志
logging:
   level:
      root: info